# Generated by Django 5.0.1 on 2026-01-08 03:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="MAC address do ESP32",
                        max_length=50,
                        unique=True,
                        verbose_name="ID do Dispositivo",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperatura"),
                            ("humidity", "Umidade"),
                            ("both", "Temperatura e Umidade"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="Tipo de Sensor",
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="Online"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Atividade"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="core.room",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor",
                "verbose_name_plural": "Sensores",
                "ordering": ["room", "name"],
            },
        ),
        migrations.CreateModel(
            name="AggregatedReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("hour", models.DateTimeField(db_index=True, verbose_name="Hora")),
                (
                    "temp_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temp. Mínima"
                    ),
                ),
                (
                    "temp_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temp. Máxima"
                    ),
                ),
                (
                    "temp_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temp. Média"
                    ),
                ),
                (
                    "humidity_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Umidade Mínima"
                    ),
                ),
                (
                    "humidity_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Umidade Máxima"
                    ),
                ),
                (
                    "humidity_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Umidade Média"
                    ),
                ),
                (
                    "reading_count",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de Leituras"
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregated_readings",
                        to="sensors.sensor",
                        verbose_name="Sensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura Agregada",
                "verbose_name_plural": "Leituras Agregadas",
                "ordering": ["-hour"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "-hour"],
                        name="sensors_agg_sensor__48fdb3_idx",
                    )
                ],
                "unique_together": {("sensor", "hour")},
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temperatura (°C)"
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Umidade (%)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="sensors.sensor",
                        verbose_name="Sensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura do Sensor",
                "verbose_name_plural": "Leituras dos Sensores",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["sensor", "-timestamp"],
                        name="sensors_sen_sensor__d03b31_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="sensors_sen_timesta_557074_idx"
                    ),
                ],
            },
        ),
    ]
