# Generated by Django 5.0.1 on 2026-01-08 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("high_temp", "Temperatura Alta"),
                            ("low_temp", "Temperatura Baixa"),
                            ("high_humidity", "Umidade Alta"),
                            ("low_humidity", "Umidade Baixa"),
                            ("sensor_offline", "Sensor Offline"),
                            ("ac_error", "Erro no Ar-Condicionado"),
                            ("system_error", "Erro do Sistema"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Alerta",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("warning", "Aviso"),
                            ("critical", "Crítico"),
                        ],
                        default="warning",
                        max_length=20,
                        verbose_name="Severidade",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "is_acknowledged",
                    models.BooleanField(default=False, verbose_name="Reconhecido"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reconhecido Em"
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reconhecido Por",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.room",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "-created_at"],
                        name="alerts_aler_room_id_0dfae9_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="alerts_aler_severit_f1bbe4_idx",
                    ),
                    models.Index(
                        fields=["is_acknowledged", "-created_at"],
                        name="alerts_aler_is_ackn_3fd880_idx",
                    ),
                ],
            },
        ),
    ]
