# Generated by Django 5.0.1 on 2026-01-08 03:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AirConditioner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on", "Ligado"),
                            ("off", "Desligado"),
                            ("error", "Erro"),
                        ],
                        default="off",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ir_code",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Códigos IR gravados para diferentes comandos",
                        verbose_name="Códigos IR",
                    ),
                ),
                (
                    "last_command",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Comando"
                    ),
                ),
                (
                    "esp32_device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MAC address do ESP32 que controla este AC",
                        max_length=50,
                        verbose_name="ID do ESP32 Transmissor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="air_conditioners",
                        to="core.room",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ar-Condicionado",
                "verbose_name_plural": "Ar-Condicionados",
                "ordering": ["room", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("command", models.CharField(max_length=50, verbose_name="Comando")),
                ("success", models.BooleanField(default=True, verbose_name="Sucesso")),
                (
                    "response",
                    models.TextField(blank=True, default="", verbose_name="Resposta"),
                ),
                (
                    "automatic",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se foi executado automaticamente",
                        verbose_name="Automático",
                    ),
                ),
                (
                    "air_conditioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="command_logs",
                        to="devices.airconditioner",
                        verbose_name="Ar-Condicionado",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_commands",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Comando",
                "verbose_name_plural": "Logs de Comandos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["air_conditioner", "-created_at"],
                        name="devices_com_air_con_7ece3f_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="devices_com_created_577af9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IRSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("power_on", "Ligar"),
                            ("power_off", "Desligar"),
                            ("temp_up", "Aumentar Temperatura"),
                            ("temp_down", "Diminuir Temperatura"),
                            ("mode_cool", "Modo Refrigeração"),
                            ("mode_heat", "Modo Aquecimento"),
                            ("mode_auto", "Modo Automático"),
                            ("fan_low", "Ventilação Baixa"),
                            ("fan_med", "Ventilação Média"),
                            ("fan_high", "Ventilação Alta"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Comando",
                    ),
                ),
                (
                    "raw_signal",
                    models.TextField(
                        help_text="Dados brutos do sinal IR", verbose_name="Sinal Raw"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Protocolo IR",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "air_conditioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ir_signals",
                        to="devices.airconditioner",
                        verbose_name="Ar-Condicionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sinal IR",
                "verbose_name_plural": "Sinais IR",
                "ordering": ["air_conditioner", "command_type"],
                "unique_together": {("air_conditioner", "command_type")},
            },
        ),
    ]
